{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "79956fad-1d86-4515-96aa-10c65fcb448f",
   "metadata": {},
   "source": [
    "\n",
    "-------------------------------------------------------------------------------\n",
    "GEOLOGICAL TIMELAPSE GENERATOR (Google Earth Engine)\n",
    "-------------------------------------------------------------------------------\n",
    "A Python tool for geologists to generate high-resolution, scientific-grade timelapses of depositional environments (deltas, inlets, canyon erosion) using 40 years of Landsat satellite data.<br>\n",
    "\n",
    "Author: Brian Willis (programmed to a large extent by Gemini AI)<br>\n",
    "AI programming support: Gemini 3 pro<br>\n",
    "Contact: Willis77019@gmail.com<br>\n",
    "License:  MIT License (unrestricted: Use at your own risk)<br>\n",
    "\n",
    "# Overview\n",
    "This script uses the Google Earth Engine (GEE) API to process satellite imagery in the cloud. It is designed to:<br>\n",
    "•\tRemove Clouds: Uses a \"surgical\" pixel QA mask to remove clouds and shadows.<br>\n",
    "•\tFix Defects: Automatically skips broken Landsat 7 data (scan line failure) to ensure clean images.<br>\n",
    "•\tEnhance Geology: Offers a \"Geology Mode\" (False Color SWIR/NIR/Red) to highlight moisture, vegetation, and lithology differences.<br>\n",
    "•\tExport 4K-Ready Frames: Generates a sequence of GeoTIFFs suitable for professional video editing (DaVinci Resolve, Premiere).<br>\n",
    "________________________________________\n",
    "# Prerequisites\n",
    "\n",
    "Before running this code, you must have a Google Earth Engine account.<br>\n",
    "A. Sign Up for Earth Engine<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tGo to the Earth Engine Sign-Up Page.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tLog in with your Google Account.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tComplete the form.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tOrganization: \"Personal\" or your university/company.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tProject Use: \"Geological research and visualization.\"<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tNote: Approval is usually instantaneous but can sometimes take a few days.<br>\n",
    "<br>\n",
    "2. Create a Cloud Project<br>\n",
    "Google requires a \"Cloud Project\" to track your requests. This is free for research/educational use.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tVisit the Earth Engine Code Editor.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tIf prompted, click \"Register a new Cloud Project\".<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tGive it a simple name (e.g., geology-timelapse-project).<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tImportant: Copy this Project ID (e.g., geology-timelapse-project). You will need to paste it into the script.<br>\n",
    "<br>\n",
    "3. Install the EarthEngine Library in your Python environment <br>\n",
    "(if you use Colab this will already be installed)<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o Open your terminal (or command prompt) and run:<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;pip install earthengine-api<br>\n",
    "One More Local python envionment \"Gotcha\": Authentication<br>\n",
    "When you run this locally for the first time after installing, the ee.Authenticate() line will likely open a browser window.\n",
    "It will ask you to log in. It will give you a code (or ask you to create a local token). Follow the instructions in the terminal. You only have to do this once on your computer. After that, the script will run automatically.\n",
    "\n",
    "________________________________________\n",
    "# How to Run (No Installation Required)\n",
    "The easiest way to run this tool is using Google Colab, which runs Python in your browser without installing anything on your computer.<br>\n",
    "1.\tClick Here to Open a New Colab Notebook.<br>\n",
    "2.\tCopy the script code below.<br>\n",
    "3.\tPaste it into the main code cell.<br>\n",
    "4.\tConfigure the Settings at the top of the script:<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tUpdate PROJECT_ID with your own project name.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tChange CENTER_LAT / CENTER_LON to your target site.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o\tSet VISUALIZATION_MODE to 'GEOLOGY' or 'TRUE_COLOR'.<br>\n",
    "5.\tClick the \"Play\" (Run) button.<br>\n",
    "6.\tAuthorize: A pop-up will ask for permission to access your Google Drive. Check the boxes and click \"Continue.\"<br>\n",
    "7.\tWait: The script will submit export tasks to Google's servers.<br>\n",
    "8.\tDownload: After ~10-15 minutes, check your Google Drive for a folder named EarthEngine_Timelapse_Exports. It will contain the high-res images.<br>\n",
    "\n",
    "This can also be run locally on JupyterLab of other python environment by installing the EarthEngine Library (see above)\n",
    "____________________________________________\n",
    "# Notes\n",
    "One way to look for areas with interesting time lapse imagery is to look at the google earth video<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;https://earthengine.google.com/timelapse/ <br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;Follow the \" Head to Google Earth to explore more\" link.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;In Google Earth right click to \"copy coodinates\" (Enter these coodinates inot the script below)<br>\n",
    "    \n",
    "Tips for Post-Processing<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o Smoothing: Use AI Frame Interpolation (like Flowframes or DaVinci Resolve Optical Flow) to smooth the jump between the annual images.<br>\n",
    "&nbsp;&nbsp;&nbsp;&nbsp;o Gap Year: The year 2012 is skipped because Landsat 5 was decommissioned and Landsat 8 had not launched. Interpolation software handles this 2-year jump easily.<br>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2310a80f-9dea-4422-9c5e-b9a958dcba56",
   "metadata": {},
   "outputs": [],
   "source": [
    "import ee\n",
    "\n",
    "# ==========================================\n",
    "#      SECTION 1: USER CONFIGURATION\n",
    "#      (Edit these values for each new site)\n",
    "# ==========================================\n",
    "\n",
    "# 1. VISUALIZATION MODE\n",
    "#    'GEOLOGY'    = False Color (SWIR/NIR/Red) -> Best for ridges, water limits, sediment.\n",
    "#    'TRUE_COLOR' = Standard Photography (Red/Green/Blue) -> Best for general audiences.\n",
    "VISUALIZATION_MODE = 'GEOLOGY' \n",
    "\n",
    "# 2. LOCATION (Decimal Degrees)\n",
    "#    Example: North Topsail Beach, NC\n",
    "CENTER_LAT = 34.63087\n",
    "CENTER_LON = -77.153\n",
    "\n",
    "# 3. ZOOM / BOX SIZE (in Degrees)\n",
    "#    0.10 = ~11 km (Inlet), 0.25 = ~27 km (Delta), 0.50 = ~55 km (Regional)\n",
    "BOX_SIZE = 0.15\n",
    "\n",
    "# 4. DATE RANGE\n",
    "#    (Note: The script AUTOMATICALLY skips 2012 due to data gaps)\n",
    "START_YEAR = 1985\n",
    "END_YEAR = 2023\n",
    "\n",
    "# 5. SEASONAL FILTER (Month Numbers)\n",
    "#    Use the Dry/Summer season to minimize clouds and vegetation noise.\n",
    "#    North America Summer: 6 (June) to 9 (Sept)\n",
    "START_MONTH = 6\n",
    "END_MONTH = 9\n",
    "\n",
    "# 6. PROJECT ID\n",
    "#    IMPORTANT: Replace this with YOUR Earth Engine Project ID.\n",
    "PROJECT_ID = 'INSERT_YOUR_PROJECT_ID_HERE'\n",
    "\n",
    "# ==========================================\n",
    "#      SECTION 2: SYSTEM SETUP\n",
    "#      (Do not edit below this line)\n",
    "# ==========================================\n",
    "\n",
    "try:\n",
    "    ee.Initialize(project=PROJECT_ID)\n",
    "except Exception:\n",
    "    ee.Authenticate()\n",
    "    ee.Initialize(project=PROJECT_ID)\n",
    "\n",
    "roi = ee.Geometry.Rectangle([\n",
    "    CENTER_LON - BOX_SIZE/2, CENTER_LAT - BOX_SIZE/2,\n",
    "    CENTER_LON + BOX_SIZE/2, CENTER_LAT + BOX_SIZE/2\n",
    "])\n",
    "\n",
    "print(f\"Target: {CENTER_LAT}, {CENTER_LON} | Mode: {VISUALIZATION_MODE}\")\n",
    "\n",
    "# ==========================================\n",
    "#      SECTION 3: PROCESSING FUNCTIONS\n",
    "# ==========================================\n",
    "\n",
    "def mask_clouds(image):\n",
    "    \"\"\"\n",
    "    Surgically removes clouds/shadows using the QA_PIXEL band.\n",
    "    \"\"\"\n",
    "    qa = image.select('QA_PIXEL')\n",
    "    mask = qa.bitwiseAnd(1<<1).eq(0).And(qa.bitwiseAnd(1<<3).eq(0).And(qa.bitwiseAnd(1<<4).eq(0)))\n",
    "    return image.updateMask(mask)\n",
    "\n",
    "def apply_scale_factors(image):\n",
    "    \"\"\"\n",
    "    Converts raw integer data to Reflectance (0.0 - 1.0) to prevent white screens.\n",
    "    \"\"\"\n",
    "    optical_bands = image.select('SR_B.').multiply(0.0000275).add(-0.2)\n",
    "    return image.addBands(optical_bands, None, True)\n",
    "\n",
    "def get_annual_composite(year):\n",
    "    \"\"\"\n",
    "    Generates a single, cloud-free image for the year.\n",
    "    CRITICAL: Skips Landsat 7 entirely to prevent 'Striping'.\n",
    "    \"\"\"\n",
    "    start = ee.Date.fromYMD(year, START_MONTH, 1)\n",
    "    end = ee.Date.fromYMD(year, END_MONTH, 30)\n",
    "\n",
    "    # Define Bands based on User Choice\n",
    "    if VISUALIZATION_MODE == 'GEOLOGY':\n",
    "        # False Color (SWIR1, NIR, Red)\n",
    "        l8_bands = ['SR_B6', 'SR_B5', 'SR_B4'] # L8/9 Source\n",
    "        l5_bands = ['SR_B5', 'SR_B4', 'SR_B3'] # L5 Source\n",
    "        out_names = ['Red_Ch', 'Green_Ch', 'Blue_Ch'] # Standardized Output\n",
    "    else:\n",
    "        # True Color (Red, Green, Blue)\n",
    "        l8_bands = ['SR_B4', 'SR_B3', 'SR_B2']\n",
    "        l5_bands = ['SR_B3', 'SR_B2', 'SR_B1']\n",
    "        out_names = ['Red_Ch', 'Green_Ch', 'Blue_Ch']\n",
    "\n",
    "    # A. LANDSAT 8 & 9 (Modern)\n",
    "    l89 = (ee.ImageCollection(\"LANDSAT/LC08/C02/T1_L2\")\n",
    "           .merge(ee.ImageCollection(\"LANDSAT/LC09/C02/T1_L2\"))\n",
    "           .filterDate(start, end).filterBounds(roi)\n",
    "           .map(mask_clouds).map(apply_scale_factors)\n",
    "           .map(lambda img: img.select(l8_bands).rename(out_names)))\n",
    "\n",
    "    # B. LANDSAT 5 (Historic) - NO LANDSAT 7 INCLUDED\n",
    "    l5 = (ee.ImageCollection(\"LANDSAT/LT05/C02/T1_L2\")\n",
    "           .filterDate(start, end).filterBounds(roi)\n",
    "           .map(mask_clouds).map(apply_scale_factors)\n",
    "           .map(lambda img: img.select(l5_bands).rename(out_names)))\n",
    "\n",
    "    return l89.merge(l5).median().clip(roi).set('year', year)\n",
    "\n",
    "# ==========================================\n",
    "#      SECTION 4: EXPORT EXECUTION\n",
    "# ==========================================\n",
    "\n",
    "# Visualization Parameters\n",
    "if VISUALIZATION_MODE == 'GEOLOGY':\n",
    "    vis_params = {'bands': ['Red_Ch', 'Green_Ch', 'Blue_Ch'], 'min': 0.0, 'max': 0.45, 'gamma': 1.4}\n",
    "else:\n",
    "    vis_params = {'bands': ['Red_Ch', 'Green_Ch', 'Blue_Ch'], 'min': 0.0, 'max': 0.20, 'gamma': 1.2}\n",
    "\n",
    "print(\"Starting Processing...\")\n",
    "# Generate list of years, EXCLUDING 2012 (Data Gap)\n",
    "years = [y for y in range(START_YEAR, END_YEAR + 1) if y != 2012]\n",
    "\n",
    "for year in years:\n",
    "    try:\n",
    "        img = get_annual_composite(year)\n",
    "        rgb_img = img.visualize(**vis_params)\n",
    "        \n",
    "        # Filename includes location, mode, and year\n",
    "        safe_mode = \"GEO\" if VISUALIZATION_MODE == 'GEOLOGY' else \"RGB\"\n",
    "        fname = f\"Site_{safe_mode}_{str(CENTER_LAT).replace('.','p')}_{year}\"\n",
    "        \n",
    "        task = ee.batch.Export.image.toDrive(\n",
    "            image=rgb_img, description=fname, folder='EarthEngine_Timelapse_Exports',\n",
    "            region=roi, scale=30, fileFormat='GeoTIFF'\n",
    "        )\n",
    "        task.start()\n",
    "        print(f\"Submitted task: {year}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error on {year}: {e}\")\n",
    "\n",
    "print(\"\\nAll tasks submitted! Check Drive folder 'EarthEngine_Timelapse_Exports'.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
