{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de55f1c8-5e4e-4d27-8611-9d3cedf9ea06",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6c02343e-4c66-49f3-ad55-0e7bf540127e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- HDR BATCH PROCESSOR STARTING ---\n",
      "Please select your INPUT folder from the popup window...\n",
      "No images found in C:/Users/Willi/Desktop/HDR TST/Stop\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "-------------------------------------------------------------------------------\n",
    "HDR BATCHER (UNIVERSAL RAW SUPPORT)\n",
    "-------------------------------------------------------------------------------\n",
    "Author:       Brian Willis\n",
    "Assisted by:  Gemini AI\n",
    "License:      MIT License \n",
    "\n",
    "DESCRIPTION:\n",
    "Batch processes image brackets into HDRs.\n",
    "Supports: JPG, TIF, PNG, and RAW formats (Canon CR3, Sony ARW, Adobe DNG).\n",
    "Method: Uses 'rawpy' for developing Raw data and OpenCV Mertens Fusion for HDR.\n",
    "\n",
    "PREREQUISITES:\n",
    "- pip install rawpy opencv-python numpy\n",
    "-------------------------------------------------------------------------------\n",
    "\"\"\"\n",
    "\n",
    "import os\n",
    "import sys\n",
    "import glob\n",
    "import time\n",
    "import cv2\n",
    "import numpy as np\n",
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "\n",
    "# Check for rawpy library\n",
    "try:\n",
    "    import rawpy\n",
    "except ImportError:\n",
    "    print(\"Missing library! Please run:\")\n",
    "    print(\"pip install rawpy\")\n",
    "    sys.exit()\n",
    "\n",
    "def load_image_safe(file_path):\n",
    "    \"\"\"\n",
    "    Smart loader: Handles both standard images and Raw files.\n",
    "    Returns: BGR numpy array (ready for OpenCV) or None.\n",
    "    \"\"\"\n",
    "    ext = os.path.splitext(file_path)[1].lower()\n",
    "    \n",
    "    # 1. Handle RAW files (CR3, ARW, DNG, NEF, ORF)\n",
    "    if ext in ['.cr3', '.arw', '.dng', '.nef', '.orf']:\n",
    "        try:\n",
    "            print(f\"    Developing Raw: {os.path.basename(file_path)}...\")\n",
    "            with rawpy.imread(file_path) as raw:\n",
    "                # Postprocess: Develop raw data to RGB\n",
    "                # use_camera_wb=True: Use the camera's white balance setting\n",
    "                # no_auto_bright=True: Prevent auto-leveling (important for HDR brackets)\n",
    "                rgb = raw.postprocess(use_camera_wb=True, no_auto_bright=True)\n",
    "                \n",
    "                # Convert RGB (Standard) to BGR (OpenCV format)\n",
    "                bgr = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)\n",
    "                return bgr\n",
    "        except Exception as e:\n",
    "            print(f\"    [ERROR] Raw decode failed: {os.path.basename(file_path)} ({e})\")\n",
    "            return None\n",
    "\n",
    "    # 2. Handle Standard files (JPG, TIF, PNG)\n",
    "    else:\n",
    "        return cv2.imread(file_path)\n",
    "\n",
    "def merge_hdr(image_list, output_path):\n",
    "    \"\"\"\n",
    "    Merges a list of loaded images using Mertens Fusion.\n",
    "    \"\"\"\n",
    "    if len(image_list) < 2:\n",
    "        print(\"    [SKIP] Need at least 2 valid images to merge.\")\n",
    "        return\n",
    "\n",
    "    print(\"    Merging (Mertens Fusion)...\")\n",
    "    \n",
    "    # Create the merger\n",
    "    merge_mertens = cv2.createMergeMertens()\n",
    "    \n",
    "    # Generate the fusion\n",
    "    res_mertens = merge_mertens.process(image_list)\n",
    "    \n",
    "    # Convert result (0-1 float) to 8-bit (0-255) for saving\n",
    "    res_8bit = np.clip(res_mertens * 255, 0, 255).astype('uint8')\n",
    "    \n",
    "    print(f\"    Saving: {os.path.basename(output_path)}\")\n",
    "    cv2.imwrite(output_path, res_8bit)\n",
    "\n",
    "def main():\n",
    "    print(\"--- HDR BATCHER (UNIVERSAL) ---\")\n",
    "    \n",
    "    # 1. Select Folder\n",
    "    root = tk.Tk()\n",
    "    root.withdraw()\n",
    "    print(\"Select the folder containing your bracketed images...\")\n",
    "    folder = filedialog.askdirectory(title=\"Select Input Folder\")\n",
    "    if not folder: return\n",
    "\n",
    "    # 2. Find Files\n",
    "    # Look for both standard and RAW formats\n",
    "    extensions = ['*.tif', '*.tiff', '*.jpg', '*.jpeg', '*.png', '*.cr3', '*.arw', '*.dng']\n",
    "    files = []\n",
    "    for ext in extensions:\n",
    "        files.extend(glob.glob(os.path.join(folder, ext)))\n",
    "        files.extend(glob.glob(os.path.join(folder, ext.upper())))\n",
    "    \n",
    "    files = sorted(list(set(files)))\n",
    "    if not files:\n",
    "        print(\"No images found.\")\n",
    "        return\n",
    "\n",
    "    print(f\"Found {len(files)} total files.\")\n",
    "\n",
    "    # 3. GROUPING LOGIC\n",
    "    # Assumes files are named like \"Site1_01.jpg\", \"Site1_02.jpg\"\n",
    "    # We group by removing the last part after the underscore.\n",
    "    \n",
    "    groups = {}\n",
    "    for f in files:\n",
    "        filename = os.path.basename(f)\n",
    "        name_no_ext = os.path.splitext(filename)[0]\n",
    "        \n",
    "        # Logic: If filename has an underscore, split at the last one.\n",
    "        # Example: \"IMG_1234_1.CR3\" -> Group ID: \"IMG_1234\"\n",
    "        if '_' in name_no_ext:\n",
    "            group_id = name_no_ext.rsplit('_', 1)[0]\n",
    "        else:\n",
    "            # Fallback: if no underscore, treat as single file (won't merge)\n",
    "            group_id = name_no_ext \n",
    "            \n",
    "        if group_id not in groups:\n",
    "            groups[group_id] = []\n",
    "        groups[group_id].append(f)\n",
    "\n",
    "    print(f\"Detected {len(groups)} bracket sets.\")\n",
    "    \n",
    "    # 4. Process Each Group\n",
    "    processed_count = 0\n",
    "    start_time = time.time()\n",
    "    \n",
    "    for i, (group_name, file_paths) in enumerate(groups.items()):\n",
    "        if len(file_paths) < 2:\n",
    "            continue\n",
    "            \n",
    "        print(f\"\\n[Group {i+1}/{len(groups)}] {group_name} ({len(file_paths)} shots)\")\n",
    "        \n",
    "        # Load images for this group\n",
    "        loaded_imgs = []\n",
    "        for fp in file_paths:\n",
    "            img = load_image_safe(fp)\n",
    "            if img is not None:\n",
    "                loaded_imgs.append(img)\n",
    "        \n",
    "        # Merge if we successfully loaded brackets\n",
    "        if loaded_imgs:\n",
    "            output_filename = f\"HDR_{group_name}.jpg\"\n",
    "            output_full_path = os.path.join(folder, output_filename)\n",
    "            merge_hdr(loaded_imgs, output_full_path)\n",
    "            processed_count += 1\n",
    "            \n",
    "            # Free memory immediately\n",
    "            del loaded_imgs\n",
    "\n",
    "    elapsed = (time.time() - start_time) / 60\n",
    "    print(f\"\\n--- BATCH COMPLETE ---\")\n",
    "    print(f\"Created {processed_count} HDRs in {elapsed:.1f} minutes.\")\n",
    "    input(\"Press Enter to exit...\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "31b0bbfc-abf3-47d7-847e-8390d5815d4c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
