{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de55f1c8-5e4e-4d27-8611-9d3cedf9ea06",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6c02343e-4c66-49f3-ad55-0e7bf540127e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- HDR BATCH PROCESSOR STARTING ---\n",
      "Please select your INPUT folder from the popup window...\n",
      "No images found in C:/Users/Willi/Desktop/HDR TST/Stop\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "-------------------------------------------------------------------------------\n",
    "HDR BATCH PROCESSOR\n",
    "-------------------------------------------------------------------------------\n",
    "A program to batch process HDR images<br>\n",
    "Author: Brian Willis<br>\n",
    "AI programming support: Gemini 3 pro<br>\n",
    "Contact: Willis77019@gmail.com<br>\n",
    "License:  MIT License (unrestricted: Use at your own risk)<br>\n",
    "\n",
    "DESCRIPTION:\n",
    "This script processes sets of photos to create High Dynamic Range (HDR) images\n",
    "or Focus Stacks using Hugin's command-line tools. It supports .JPG and Nikon \n",
    "RAW (.NEF) files. The script employs robust error checking. \n",
    "\n",
    "If a set of bracketed photos cannot be aligned mathematically (due to extreme movement \n",
    "or lack of overlapping detail between exposures), the script will skip that set and \n",
    "provide a log detail explaining why, rather than crashing the entire batch.\n",
    "\n",
    "PREREQUISITES:\n",
    "1. Hugin Panorama Stitcher must be installed.\n",
    "   - Point the script to the 'bin' directory containing \"align_image_stack\".\n",
    "2. Python Libraries:\n",
    "   - pip install rawpy imageio exifread\n",
    "\n",
    "CONFIGURATION GUIDE:\n",
    "- HDR Mode (Default): Keeps --exposure-weight=1.0 and --contrast-weight=0.0.\n",
    "- Focus Stacking: Flip weights (--exposure-weight=0.0, --contrast-weight=1.0).\n",
    "-------------------------------------------------------------------------------\n",
    "\"\"\"\n",
    "\n",
    "import os\n",
    "import subprocess\n",
    "import glob\n",
    "import datetime\n",
    "import shutil\n",
    "import platform\n",
    "import sys\n",
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "\n",
    "# ================= USER CONFIGURATION =================\n",
    "\n",
    "# 1. HUGIN PATH DETECTION\n",
    "# Auto-detects OS to set the correct path and extension (.exe)\n",
    "if platform.system() == \"Windows\":\n",
    "    HUGIN_EXEC_EXT = \".exe\"\n",
    "    # Default Windows path (Change if you installed Hugin elsewhere)\n",
    "    HUGIN_BIN_PATH = r\"C:\\Program Files\\Hugin\\bin\" \n",
    "elif platform.system() == \"Darwin\": # Mac\n",
    "    HUGIN_EXEC_EXT = \"\"\n",
    "    HUGIN_BIN_PATH = \"/Applications/Hugin/HuginTools\"\n",
    "else: # Linux\n",
    "    HUGIN_EXEC_EXT = \"\"\n",
    "    HUGIN_BIN_PATH = \"/usr/bin\"\n",
    "\n",
    "# 2. GROUPING SETTINGS\n",
    "# 'TIME': Groups photos by time bursts (BURST_THRESHOLD seconds apart).\n",
    "# 'FIXED': Forces groups of a specific count (e.g. 3 photos per HDR).\n",
    "GROUP_METHOD = 'FIXED' \n",
    "BURST_THRESHOLD = 2.0  # Seconds between bursts (for TIME mode)\n",
    "FIXED_COUNT = 3        # Photos per set (for FIXED mode)\n",
    "\n",
    "# 3. PROCESSING SETTINGS\n",
    "# True = HDR (Exposure Blending). False = Focus Stacking (Contrast Blending).\n",
    "DO_HDR_BLENDING = True \n",
    "\n",
    "# ======================================================\n",
    "\n",
    "def get_timestamp(file_path):\n",
    "    import exifread\n",
    "    try:\n",
    "        with open(file_path, 'rb') as f:\n",
    "            tags = exifread.process_file(f, stop_tag='EXIF DateTimeOriginal')\n",
    "            date_str = str(tags.get('EXIF DateTimeOriginal'))\n",
    "            return datetime.datetime.strptime(date_str, '%Y:%m:%d %H:%M:%S')\n",
    "    except:\n",
    "        return datetime.datetime.fromtimestamp(os.path.getmtime(file_path))\n",
    "\n",
    "def check_hugin_install():\n",
    "    test_tool = os.path.join(HUGIN_BIN_PATH, f\"align_image_stack{HUGIN_EXEC_EXT}\")\n",
    "    if not os.path.exists(test_tool):\n",
    "        print(\"!!!\" * 10)\n",
    "        print(f\"ERROR: Hugin tool not found at: {test_tool}\")\n",
    "        print(\"Please edit 'HUGIN_BIN_PATH' in the script configuration.\")\n",
    "        print(\"!!!\" * 10)\n",
    "        return False\n",
    "    return True\n",
    "\n",
    "def process_set(group, output_folder, set_index):\n",
    "    # 1. Setup paths\n",
    "    base_name = os.path.splitext(os.path.basename(group[0]))[0]\n",
    "    output_filename = f\"HDR_{base_name}.tif\"\n",
    "    output_path = os.path.join(output_folder, output_filename)\n",
    "    \n",
    "    print(f\"  -> Processing set {set_index} ({len(group)} images)...\")\n",
    "    \n",
    "    align_tool = os.path.join(HUGIN_BIN_PATH, f\"align_image_stack{HUGIN_EXEC_EXT}\")\n",
    "    enfuse_tool = os.path.join(HUGIN_BIN_PATH, f\"enfuse{HUGIN_EXEC_EXT}\")\n",
    "    \n",
    "    # === STEP 1: DEVELOP RAWs TO TEMP TIFs ===\n",
    "    # align_image_stack often fails on NEFs directly. We must feed it TIFs.\n",
    "    temp_input_tifs = []\n",
    "    \n",
    "    try:\n",
    "        import rawpy\n",
    "        import imageio\n",
    "        \n",
    "        for raw_file in group:\n",
    "            # Create a temp filename in the output folder\n",
    "            fname = os.path.basename(raw_file)\n",
    "            tif_name = os.path.join(output_folder, f\"temp_dev_{fname}.tif\")\n",
    "            \n",
    "            # Skip conversion if input is already TIF/JPG\n",
    "            if raw_file.lower().endswith(('.tif', '.tiff', '.jpg', '.jpeg')):\n",
    "                temp_input_tifs.append(raw_file)\n",
    "                continue\n",
    "                \n",
    "            # Develop NEF to TIF\n",
    "            # use_camera_wb=True: Keeps colors looking natural\n",
    "            # no_auto_bright=True: CRITICAL. Preserves the exposure difference between brackets!\n",
    "            with rawpy.imread(raw_file) as raw:\n",
    "                rgb = raw.postprocess(use_camera_wb=True, no_auto_bright=True, bright=1.0, user_sat=None)\n",
    "                imageio.imsave(tif_name, rgb)\n",
    "                temp_input_tifs.append(tif_name)\n",
    "                \n",
    "    except Exception as e:\n",
    "        print(f\"    [ERROR] Failed to convert RAW: {e}\")\n",
    "        return\n",
    "\n",
    "    # === STEP 2: ALIGN IMAGES ===\n",
    "    # Now we feed the TIFs to align_image_stack\n",
    "    cmd_align = [align_tool, \"-m\", \"-a\", \"temp_aligned_\", \"-c\", \"24\", \"-v\"] \n",
    "    cmd_align.extend([os.path.basename(f) for f in temp_input_tifs]) # Use filenames only\n",
    "    \n",
    "    try:\n",
    "        # Run Hugin inside the output folder\n",
    "        result = subprocess.run(\n",
    "            cmd_align, \n",
    "            cwd=output_folder,\n",
    "            capture_output=True,\n",
    "            text=True\n",
    "        )\n",
    "        \n",
    "        if result.returncode != 0:\n",
    "            print(\"    [ERROR] Alignment failed.\")\n",
    "            print(f\"    [HUGIN LOG] {result.stderr[:400]}\") # Print more error info\n",
    "            # Cleanup temp input tifs before returning\n",
    "            for f in temp_input_tifs:\n",
    "                if \"temp_dev_\" in f: os.remove(f)\n",
    "            return\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"    [SYSTEM ERROR] {e}\")\n",
    "        return\n",
    "\n",
    "    # Find the aligned TIFs created by Hugin\n",
    "    aligned_files = sorted(glob.glob(os.path.join(output_folder, \"temp_aligned_*.tif\")))\n",
    "    \n",
    "    if not aligned_files:\n",
    "        print(\"    [ERROR] No aligned files created (Silent Failure).\")\n",
    "        # Cleanup temp input tifs\n",
    "        for f in temp_input_tifs:\n",
    "            if \"temp_dev_\" in f: os.remove(f)\n",
    "        return\n",
    "\n",
    "    # === STEP 3: ENFUSE (BLEND) ===\n",
    "    if DO_HDR_BLENDING:\n",
    "        exp_w, cont_w = \"1.0\", \"0.0\"\n",
    "    else:\n",
    "        exp_w, cont_w = \"0.0\", \"1.0\"\n",
    "\n",
    "    cmd_enfuse = [enfuse_tool, \"--output\", output_filename,\n",
    "           f\"--exposure-weight={exp_w}\", \n",
    "           f\"--saturation-weight=0.2\", \n",
    "           f\"--contrast-weight={cont_w}\", \n",
    "           \"--soft-mask\"]\n",
    "    cmd_enfuse.extend([os.path.basename(f) for f in aligned_files])\n",
    "    \n",
    "    subprocess.call(cmd_enfuse, cwd=output_folder)\n",
    "    \n",
    "    # === CLEANUP ===\n",
    "    # Delete the \"temp_dev\" TIFs and the \"temp_aligned\" TIFs\n",
    "    for f in aligned_files:\n",
    "        try: os.remove(f)\n",
    "        except: pass\n",
    "        \n",
    "    for f in temp_input_tifs:\n",
    "        # Only delete files we created (containing \"temp_dev_\")\n",
    "        if \"temp_dev_\" in f:\n",
    "            try: os.remove(f)\n",
    "            except: pass\n",
    "        \n",
    "    print(f\"    [DONE] Saved to: {output_filename}\")\n",
    "\n",
    "def main():\n",
    "    print(\"--- HDR BATCH PROCESSOR STARTING ---\")\n",
    "    if not check_hugin_install(): return\n",
    "\n",
    "    # Windows Folder Picker\n",
    "    root = tk.Tk()\n",
    "    root.withdraw() # Hide the main window\n",
    "    print(\"Please select your INPUT folder from the popup window...\")\n",
    "    INPUT_FOLDER = filedialog.askdirectory(title=\"Select Input Folder Containing Photos\")\n",
    "    \n",
    "    if not INPUT_FOLDER:\n",
    "        print(\"No folder selected. Exiting.\")\n",
    "        return\n",
    "\n",
    "    OUTPUT_FOLDER = os.path.join(INPUT_FOLDER, \"Processed_HDR\")\n",
    "    if not os.path.exists(OUTPUT_FOLDER): os.makedirs(OUTPUT_FOLDER)\n",
    "\n",
    "    # Gather Files (Case-Insensitive to fix duplicate bugs)\n",
    "    extensions = ['*.NEF', '*.nef', '*.JPG', '*.jpg', '*.TIF', '*.tif']\n",
    "    raw_files = []\n",
    "    for ext in extensions:\n",
    "        raw_files.extend(glob.glob(os.path.join(INPUT_FOLDER, ext)))\n",
    "    \n",
    "    # Remove duplicates by normalizing to lowercase path\n",
    "    unique_files = {}\n",
    "    for f in raw_files:\n",
    "        unique_files[os.path.abspath(f).lower()] = f\n",
    "    files = sorted(list(unique_files.values()))\n",
    "\n",
    "    if not files:\n",
    "        print(f\"No images found in {INPUT_FOLDER}\")\n",
    "        return\n",
    "\n",
    "    # Grouping Logic\n",
    "    groups = []\n",
    "    if GROUP_METHOD == 'FIXED':\n",
    "        for i in range(0, len(files), FIXED_COUNT):\n",
    "            groups.append(files[i:i+FIXED_COUNT])\n",
    "    else:\n",
    "        # Time-based grouping\n",
    "        files_with_time = [(f, get_timestamp(f)) for f in files]\n",
    "        files_with_time.sort(key=lambda x: x[1])\n",
    "        \n",
    "        current_group = [files_with_time[0][0]]\n",
    "        for i in range(1, len(files_with_time)):\n",
    "            prev_time = files_with_time[i-1][1]\n",
    "            curr_file, curr_time = files_with_time[i]\n",
    "            \n",
    "            if (curr_time - prev_time).total_seconds() < BURST_THRESHOLD:\n",
    "                current_group.append(curr_file)\n",
    "            else:\n",
    "                groups.append(current_group)\n",
    "                current_group = [curr_file]\n",
    "        groups.append(current_group)\n",
    "\n",
    "    print(f\"Found {len(groups)} sets to process.\")\n",
    "    \n",
    "    for i, group in enumerate(groups):\n",
    "        if len(group) < 2:\n",
    "            print(f\"Skipping set {i+1} (Single image, need at least 2).\")\n",
    "            continue\n",
    "        process_set(group, OUTPUT_FOLDER, i+1)\n",
    "\n",
    "    print(\"--- ALL DONE ---\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "31b0bbfc-abf3-47d7-847e-8390d5815d4c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
