{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "010db421-772e-432f-8bce-6e078669c27e",
   "metadata": {},
   "source": [
    "\"\"\"\n",
    "-------------------------------------------------------------------------------\n",
    "MOVIE MAKER SCRIPT (Image Sequence to Video)\n",
    "-------------------------------------------------------------------------------\n",
    "Simple program to convert an inage sequence to a video<br>\n",
    "Author: Brian Willis<br>\n",
    "AI programming support: Gemini 3 pro<br>\n",
    "Contact: Willis77019@gmail.com<br>\n",
    "License:  MIT License (unrestricted: Use at your own risk)<br>\n",
    "\n",
    "DESCRIPTION:\n",
    "This simple script is a replacement for Microsoft's discontinued Movie Maker. \n",
    "It allows you to convert a folder of sequential image files into a single high-quality  movie file (MP4). It is particularly useful for:\n",
    "- Geological model outputs (simulation time-steps).\n",
    "- Time-lapse photography (fieldwork or lab experiments).\n",
    "- Drone flight time laspe image sequences.\n",
    "\n",
    "PREREQUISITES:\n",
    "1. Python Libraries:\n",
    "   - You must install the FFmpeg plugin for imageio.\n",
    "   - Run this in your terminal/command prompt:\n",
    "     pip install imageio[ffmpeg]\n",
    "\n",
    "PERFORMANCE NOTE:\n",
    "- This script is designed for convenience and ease of use within Python.\n",
    "- For massive datasets (e.g., 10,000+ 4K frames), the native FFmpeg command-line tool is faster, but this script handles the complexity of file sorting and encoding arguments for you.\n",
    "\n",
    "CONFIGURATION:\n",
    "- Set 'FPS' (Frames Per Second) in the script to control speed.\n",
    "  - 30 FPS = Smooth video.\n",
    "  - 0.5 FPS = Slideshow (1 image every 2 seconds).\n",
    "-------------------------------------------------------------------------------\n",
    "\"\"\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6c02343e-4c66-49f3-ad55-0e7bf540127e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- SEQUENCE TO VIDEO STARTING ---\n",
      "Please select your INPUT folder containing image frames...\n",
      "No images found in C:/Users/Willi/Desktop/HDR TST/Stop\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "-------------------------------------------------------------------------------\n",
    "MOVIE MAKER SCRIPT (Sequence to Video)\n",
    "-------------------------------------------------------------------------------\n",
    "Author:       Brian Willis (Enabled by Gemini AI)\n",
    "Contact:      Willis77019@gmail.com\n",
    "License:      MIT License \n",
    "\n",
    "DESCRIPTION:\n",
    "This script converts a folder of sequential images into an MP4 video.\n",
    "It automatically handles the \"Odd Number\" crash by cropping 1 pixel if needed.\n",
    "\n",
    "PREREQUISITES:\n",
    "- pip install imageio[ffmpeg]\n",
    "-------------------------------------------------------------------------------\n",
    "\"\"\"\n",
    "\n",
    "import os\n",
    "import glob\n",
    "import imageio.v2 as imageio # <--- Fixes the \"Deprecation\" warning\n",
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "\n",
    "# ================= USER CONFIGURATION =================\n",
    "FPS = 30       # Frames Per Second\n",
    "QUALITY = 8    # Video Quality (0-10)\n",
    "# ======================================================\n",
    "\n",
    "def main():\n",
    "    print(\"--- SEQUENCE TO VIDEO STARTING ---\")\n",
    "\n",
    "    # 1. Select Folder\n",
    "    root = tk.Tk()\n",
    "    root.withdraw()\n",
    "    print(\"Please select your INPUT folder containing image frames...\")\n",
    "    INPUT_FOLDER = filedialog.askdirectory(title=\"Select Folder With Image Sequence\")\n",
    "    \n",
    "    if not INPUT_FOLDER: return\n",
    "    \n",
    "    # 2. Setup Output\n",
    "    folder_name = os.path.basename(INPUT_FOLDER)\n",
    "    OUTPUT_FILE = os.path.join(INPUT_FOLDER, f\"{folder_name}_Video.mp4\")\n",
    "\n",
    "    # 3. Gather files\n",
    "    extensions = ['*.JPG', '*.jpg', '*.PNG', '*.png', '*.JPEG', '*.jpeg']\n",
    "    files = []\n",
    "    for ext in extensions:\n",
    "        files.extend(glob.glob(os.path.join(INPUT_FOLDER, ext)))\n",
    "    \n",
    "    files.sort() # Ensure correct order\n",
    "    \n",
    "    if not files:\n",
    "        print(f\"No images found in {INPUT_FOLDER}\")\n",
    "        return\n",
    "\n",
    "    # 4. Check Dimensions (The \"Broken Pipe\" Fix)\n",
    "    # Read the first image to check for odd numbers\n",
    "    first_img = imageio.imread(files[0])\n",
    "    height, width, _ = first_img.shape\n",
    "    \n",
    "    print(f\"Found {len(files)} frames. Source Resolution: {width}x{height}\")\n",
    "    \n",
    "    # Calculate safe dimensions (Must be divisible by 2)\n",
    "    safe_width = width\n",
    "    safe_height = height\n",
    "    \n",
    "    if width % 2 != 0: safe_width -= 1\n",
    "    if height % 2 != 0: safe_height -= 1\n",
    "    \n",
    "    if safe_width != width or safe_height != height:\n",
    "        print(f\"[WARNING] Odd resolution detected!\")\n",
    "        print(f\"  FFmpeg requires even numbers. Cropping video to: {safe_width}x{safe_height}\")\n",
    "    \n",
    "    # 5. Create Video\n",
    "    print(f\"Stitching video at {FPS} fps...\")\n",
    "    \n",
    "    try:\n",
    "        # We explicitly set macro_block_size=None because we are handling the sizing manually\n",
    "        with imageio.get_writer(OUTPUT_FILE, fps=FPS, quality=QUALITY, macro_block_size=None) as writer:\n",
    "            for i, filename in enumerate(files):\n",
    "                if i % 50 == 0:\n",
    "                    print(f\"  Processing frame {i}/{len(files)}...\", end='\\r')\n",
    "                \n",
    "                image = imageio.imread(filename)\n",
    "                \n",
    "                # CROP IF NEEDED (To satisfy the Even-Number Rule)\n",
    "                # Slicing syntax: image[0:safe_height, 0:safe_width, :]\n",
    "                if safe_width != width or safe_height != height:\n",
    "                    image = image[:safe_height, :safe_width, :]\n",
    "                \n",
    "                writer.append_data(image)\n",
    "\n",
    "        print(f\"\\n[DONE] Video saved to: {OUTPUT_FILE}\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"\\n[CRITICAL ERROR] {e}\")\n",
    "        print(\"Tip: If you see 'Broken Pipe', it usually means FFmpeg crashed.\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2a61852d-e3be-4442-8bec-0a0c2b438706",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: imageio[ffmpeg] in c:\\users\\willi\\anaconda3\\lib\\site-packages (2.37.0)Note: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "Requirement already satisfied: numpy in c:\\users\\willi\\anaconda3\\lib\\site-packages (from imageio[ffmpeg]) (2.1.3)\n",
      "Requirement already satisfied: pillow>=8.3.2 in c:\\users\\willi\\anaconda3\\lib\\site-packages (from imageio[ffmpeg]) (11.3.0)\n",
      "Requirement already satisfied: imageio-ffmpeg in c:\\users\\willi\\anaconda3\\lib\\site-packages (from imageio[ffmpeg]) (0.6.0)\n",
      "Requirement already satisfied: psutil in c:\\users\\willi\\anaconda3\\lib\\site-packages (from imageio[ffmpeg]) (5.9.0)\n"
     ]
    }
   ],
   "source": [
    "pip install imageio[ffmpeg]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a05947bc-78c0-4549-a624-80ab916ed695",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
