{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "010db421-772e-432f-8bce-6e078669c27e",
   "metadata": {},
   "source": [
    "\"\"\"\n",
    "-------------------------------------------------------------------------------\n",
    "PANORAMA BATCH STITCHER\n",
    "-------------------------------------------------------------------------------\n",
    "Batch process photomosaic construction.\n",
    "Author: Brian Willis<br>\n",
    "AI programming support: Gemini 3 pro<br>\n",
    "Contact: Willis77019@gmail.com<br>\n",
    "License:  MIT License (unrestricted: Use at your own risk)<br>\n",
    "\n",
    "DESCRIPTION:\n",
    "This script automates the stitching of multiple panoramic mosaics from a single\n",
    "folder of images. It will stitch photomosaics constructed from a single row of photos or multiple rows of photos. It supports .JPG and Nikon RAW (.NEF) files (extendable to others).\n",
    "\n",
    "PREREQUISITES:\n",
    "1. Hugin must be installed.\n",
    "   https://hugin.sourceforge.io/\n",
    "   - You must point the script to the 'bin' directory containing \"align_image_stack.exe\".\n",
    "   - Example Path: r\"C:\\Program Files\\Hugin\\bin\"\n",
    "2. Python Libraries:\n",
    "   - pip install rawpy imageio exifread\n",
    "\n",
    "IT USES THE HUGIN TOOLCHAIN:\n",
    "1. pto_gen:         Creates the project file.\n",
    "2. cpfind:          Finds matching control points in overlapping images (multi-row supported).\n",
    "3. autooptimiser:   Calculates geometry, warp, and photometric alignment.\n",
    "4. hugin_executor:  Renders the final high-resolution mosaic.\n",
    "\n",
    "SHOOTING & SETUP:\n",
    "- Optimized for ROTATIONAL stitching (standing in one spot, panning/tilting).\n",
    "- LINEAR SCANS: If you walked along an outcrop (linear translation), this script \n",
    "  may struggle with parallax. For linear scans, consider Microsoft ICE or Meshroom.\n",
    "- CLEAN DATA: The script groups images by timestamps. If you have rapid-burst \n",
    "  sequences (HDR brackets or sports mode) mixed in, the grouping logic will fail. \n",
    "  Please separate panorama sets into their own folder before processing.\n",
    "- SHOOTING PATTERN: Multi-row photomosaics are best collected by a Gigapan robot \n",
    "  for a uniform distribution. This script is made for those who wish to make handheld \n",
    "  \"Gigapan-like\" mosaics. \n",
    "  Best practice:\n",
    "  1. Ensure moderate overlap of images (30-40%).\n",
    "  2. Shoot in a snake pattern (Left->Right, Tilt Up, Right->Left).\n",
    "  3. Use a long focal length lens (preferably 85mm+ or 200mm) for flatter perspective.\n",
    "\n",
    "RUN MODES (Set in Configuration Section):\n",
    "1. Auto-Detect (Default):\n",
    "   - Uses TIME_THRESHOLD (e.g., 20.0 seconds) to detect when one mosaic ends \n",
    "     and the next begins.\n",
    "   - Requirement: You must pause for >20s between shooting different outcrops.\n",
    "2. Force Mode (FORCE_ALL_ONE_PANO = True):\n",
    "   - Treats the entire folder as a single giant mosaic.\n",
    "   - Use this for very large/long datasets where you might have paused during shooting.\n",
    "\n",
    "PERFORMANCE NOTE (The \"Go To Bed\" Rule):\n",
    "This process is computationally intensive. \n",
    "- Phase 1 (Matching) creates many \"tilted\" single images in the output folder. \n",
    "  DO NOT PANIC. These are temporary intermediate files.\n",
    "- Phase 2 (Rendering) compiles them into the final mosaic. \n",
    "- For large field seasons, it is recommended to run this script overnight.\n",
    "-------------------------------------------------------------------------------\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "6c02343e-4c66-49f3-ad55-0e7bf540127e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- PANORAMA BATCH STITCHER STARTING ---\n",
      "Please select your INPUT folder from the popup window...\n",
      "No files found!\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "-------------------------------------------------------------------------------\n",
    "PANORAMA PANNER (UNIVERSAL BATCH ENGINE)\n",
    "-------------------------------------------------------------------------------\n",
    "Author:       Brian Willis\n",
    "Assisted by:  Gemini AI\n",
    "License:      MIT License \n",
    "\n",
    "DESCRIPTION:\n",
    "The Batch version of the \"Raw Binary\" engine.\n",
    "1. Converts each image (JPG, TIF, PNG, RAW) to a raw binary stream on the SSD.\n",
    "2. Memory-maps the stream to render the video.\n",
    "3. Automatically cleans up the temp file before starting the next image.\n",
    "\n",
    "PREREQUISITES:\n",
    "- pip install imageio[ffmpeg] numpy opencv-python\n",
    "-------------------------------------------------------------------------------\n",
    "\"\"\"\n",
    "\n",
    "import os\n",
    "import sys\n",
    "import subprocess\n",
    "import re\n",
    "import time\n",
    "import glob\n",
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "\n",
    "# === LIBRARIES ===\n",
    "try:\n",
    "    import imageio_ffmpeg\n",
    "    import numpy as np\n",
    "    import cv2\n",
    "except ImportError:\n",
    "    print(\"Missing libraries! Please run:\")\n",
    "    print(\"pip install imageio[ffmpeg] numpy opencv-python\")\n",
    "    sys.exit()\n",
    "\n",
    "# === CONFIGURATION ===\n",
    "VIDEO_WIDTH = 3840   # 4K UHD\n",
    "VIDEO_HEIGHT = 2160\n",
    "FPS = 30\n",
    "DURATION = 20.0      # Duration per video in seconds\n",
    "\n",
    "# ==============================\n",
    "\n",
    "def get_image_dims(ffmpeg_exe, file_path):\n",
    "    \"\"\"Probes image dimensions using FFmpeg (Zero RAM).\"\"\"\n",
    "    try:\n",
    "        cmd = [ffmpeg_exe, \"-i\", file_path]\n",
    "        process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)\n",
    "        _, stderr = process.communicate()\n",
    "        \n",
    "        # Regex for \"Video: ..., 1234x5678, ...\"\n",
    "        match = re.search(r\", (\\d+)x(\\d+)\", stderr)\n",
    "        if not match:\n",
    "            # Fallback regex\n",
    "            match = re.search(r\"Video:.* (\\d{3,})x(\\d{3,})\", stderr)\n",
    "            \n",
    "        if match:\n",
    "            return int(match.group(1)), int(match.group(2))\n",
    "    except:\n",
    "        pass\n",
    "    return None, None\n",
    "\n",
    "def process_single_file(ffmpeg_exe, src_path, temp_raw_path):\n",
    "    \"\"\"\n",
    "    Main logic to process one image. Returns True on success.\n",
    "    \"\"\"\n",
    "    filename = os.path.basename(src_path)\n",
    "    folder = os.path.dirname(src_path)\n",
    "    name = os.path.splitext(filename)[0]\n",
    "    output_video = os.path.join(folder, f\"Video_{name}_{int(DURATION)}s.mp4\")\n",
    "\n",
    "    print(f\"\\nProcessing: {filename}...\")\n",
    "\n",
    "    try:\n",
    "        # 1. Probe Dimensions\n",
    "        w, h = get_image_dims(ffmpeg_exe, src_path)\n",
    "        if w is None:\n",
    "            print(\"  [SKIP] Could not detect dimensions (Format might be unsupported).\")\n",
    "            return False\n",
    "        \n",
    "        print(f\"  Dims: {w} x {h}\")\n",
    "\n",
    "        # 2. Convert to Raw (Save to SSD)\n",
    "        if os.path.exists(temp_raw_path):\n",
    "            try: os.remove(temp_raw_path)\n",
    "            except: pass\n",
    "\n",
    "        print(f\"  Streaming to raw temp file (SSD)...\")\n",
    "        # FFmpeg reads CR3/ARW/DNG automatically if the codec is supported\n",
    "        cmd_convert = [\n",
    "            ffmpeg_exe, \"-y\",\n",
    "            \"-i\", src_path,\n",
    "            \"-f\", \"rawvideo\",\n",
    "            \"-pix_fmt\", \"rgb24\",\n",
    "            temp_raw_path\n",
    "        ]\n",
    "        subprocess.run(cmd_convert, check=True, stderr=subprocess.DEVNULL)\n",
    "\n",
    "        # 3. Memory Map & Render\n",
    "        raw_map = np.memmap(temp_raw_path, dtype='uint8', mode='r', shape=(h, w, 3))\n",
    "        \n",
    "        # Geometry\n",
    "        crop_h = h\n",
    "        target_aspect = VIDEO_WIDTH / VIDEO_HEIGHT\n",
    "        crop_w = int(crop_h * target_aspect)\n",
    "        \n",
    "        if crop_w > w:\n",
    "            print(f\"  [SKIP] Image too narrow (Needs {crop_w}px, has {w}px).\")\n",
    "            del raw_map\n",
    "            return False\n",
    "\n",
    "        # Video Writer\n",
    "        fourcc = cv2.VideoWriter_fourcc(*'mp4v') \n",
    "        video = cv2.VideoWriter(output_video, fourcc, FPS, (VIDEO_WIDTH, VIDEO_HEIGHT))\n",
    "        \n",
    "        total_frames = int(DURATION * FPS)\n",
    "        max_pan_x = w - crop_w\n",
    "        step_per_frame = max_pan_x / total_frames\n",
    "        \n",
    "        # Render Loop\n",
    "        for i in range(total_frames):\n",
    "            curr_x = int(i * step_per_frame)\n",
    "            \n",
    "            # Read from SSD (Virtual RAM)\n",
    "            frame_raw = raw_map[0:crop_h, curr_x:curr_x+crop_w]\n",
    "            \n",
    "            # Resize\n",
    "            frame_final = cv2.resize(frame_raw, (VIDEO_WIDTH, VIDEO_HEIGHT), interpolation=cv2.INTER_LINEAR)\n",
    "            \n",
    "            # RGB -> BGR\n",
    "            frame_bgr = cv2.cvtColor(frame_final, cv2.COLOR_RGB2BGR)\n",
    "            video.write(frame_bgr)\n",
    "            \n",
    "            if i % 30 == 0 or i == total_frames - 1:\n",
    "                percent = ((i + 1) / total_frames) * 100\n",
    "                print(f\"\\r  Rendered {percent:.1f}% ({i+1}/{total_frames})\", end='')\n",
    "\n",
    "        video.release()\n",
    "        del raw_map # Close file lock\n",
    "        print(f\"\\n  [DONE] Saved video.\")\n",
    "        return True\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"\\n  [ERROR] Failed: {e}\")\n",
    "        return False\n",
    "    finally:\n",
    "        if os.path.exists(temp_raw_path):\n",
    "            try: os.remove(temp_raw_path)\n",
    "            except: pass\n",
    "\n",
    "def main():\n",
    "    print(\"--- PANORAMA PANNER (UNIVERSAL BATCH) ---\")\n",
    "    \n",
    "    ffmpeg_exe = imageio_ffmpeg.get_ffmpeg_exe()\n",
    "    temp_dir = os.environ.get('TEMP', os.path.expanduser('~'))\n",
    "    temp_raw_path = os.path.join(temp_dir, \"pano_batch_temp.raw\")\n",
    "    \n",
    "    # 1. Select Mode\n",
    "    print(\"\\nSelect Mode:\")\n",
    "    print(\"  [S] Single File\")\n",
    "    print(\"  [B] Batch Folder\")\n",
    "    mode = input(\"Choice (s/b): \").strip().lower()\n",
    "    \n",
    "    files = []\n",
    "    root = tk.Tk()\n",
    "    root.withdraw()\n",
    "\n",
    "    if mode == 'b':\n",
    "        folder = filedialog.askdirectory(title=\"Select Input Folder\")\n",
    "        if not folder: return\n",
    "        \n",
    "        # UPDATE: Added Raw formats (*.CR3, *.ARW, *.DNG) to this list\n",
    "        valid_extensions = ['*.tif', '*.tiff', '*.jpg', '*.jpeg', '*.png', '*.bmp', '*.psd', '*.cr3', '*.arw', '*.dng']\n",
    "        \n",
    "        for ext in valid_extensions:\n",
    "            files.extend(glob.glob(os.path.join(folder, ext)))\n",
    "            files.extend(glob.glob(os.path.join(folder, ext.upper())))\n",
    "            \n",
    "        files = sorted(list(set(files)))\n",
    "    else:\n",
    "        f = filedialog.askopenfilename(title=\"Select Image\")\n",
    "        if f: files = [f]\n",
    "\n",
    "    if not files: return\n",
    "\n",
    "    # 2. Batch Loop\n",
    "    print(f\"\\n--- STARTING BATCH ({len(files)} files) ---\")\n",
    "    \n",
    "    success_count = 0\n",
    "    start_batch = time.time()\n",
    "    \n",
    "    for i, f in enumerate(files):\n",
    "        print(f\"\\n[File {i+1} of {len(files)}]\")\n",
    "        if process_single_file(ffmpeg_exe, f, temp_raw_path):\n",
    "            success_count += 1\n",
    "            \n",
    "    elapsed = (time.time() - start_batch) / 60\n",
    "    print(f\"\\n--- BATCH COMPLETE ---\")\n",
    "    print(f\"Processed: {success_count}/{len(files)}\")\n",
    "    print(f\"Total Time: {elapsed:.1f} minutes\")\n",
    "    \n",
    "    input(\"Press Enter to exit...\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eff786bd-fe88-4c02-91b3-737876d151ec",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
